### ISSUE TITLE
Scale won't reset after dying

### ISSUE THREAD

**Issue by GamyGamer** [Jack-Sibley/slimeorigin#4]
As in title, after being killed scale is still the same as before death making possible to shrink even more than normal. 

Note: In Pehkui configuration file there is variable called "keepScaleOnRespawn" that is normally set on false, but I have modified it to say true.

**Comment by Jack-Sibley** [comment]
Not going to lie to it didn't even occur to me that this was something that could be turned off (makes total sense though), I'll see if I can figure out a fix.

**Comment by Jack-Sibley** [comment]
Fixed in v1.1.1. You'll have to reset the "width" and "height" scale with the `/scale reset` command manually on existing worlds with this issue.
