### ISSUE TITLE
Server crashes after death

### ISSUE THREAD

**Issue by uzervlad** [Jack-Sibley/slimeorigin#5]
Screenshot of the error:
![Screenshot_20210413-231425.jpg](https://user-images.githubusercontent.com/24654479/114615190-0eb64180-9cae-11eb-82cf-69a25be98bd3.jpg)

I'm running a server with latest fabric release and these mods
![Screenshot_20210413-231524~2.jpg](https://user-images.githubusercontent.com/24654479/114615462-68b70700-9cae-11eb-918f-c290d1b62788.jpg)

**Comment by uzervlad** [comment]
After some searching, I found out that this is a problem with Pehkui 2.0.0

**Comment by AadityaY** [comment]
Huh
I tried to run the mod with older versions of Pekhui, but I literally couldn't open my game (It crashed)

Anyone know why?
I had Fabric API, Patchouli, and several origins mods

**Comment by Rustwolfz** [comment]
I've had the same problem. Every time I die It crashes the server I'm on. I even switched pekhui versions and I was smaller but then died and it crashed. (I switched to the latest) I'm playing 1.16.5 so I used that one then used The 1.14.4-1.17. Version and I shrunk but it still crashed when I died I can't find any fixes

**Comment by Rustwolfz** [comment]
> After some searching, I found out that this is a problem with Pehkui 2.0.0
> 
> Not closing the issue yet, as either a version check should be implemented, or a note on CurseForge should be made.

So is there a specific version needed to make it work (that isn't 2.00) or is there another fix?

**Comment by uzervlad** [comment]
@Rustwolfz I used this with Pehkui 1.10.0 and everything worked fine

**Comment by uzervlad** [comment]
@AadityaY please, send your [crash reports](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report), that would help find the issue

**Comment by zombiemonarch** [comment]
I think this has to do with the new version of pehkui kicking and crashing u when u get to 0 width 0 height

**Comment by carelesshippo** [comment]
I think preventing it from being zero (changing min and fall back on slime ClampedEntityAttribute of slime size should do it

**Comment by AlpacasAreFluffy** [comment]
> @Rustwolfz I used this with Pehkui 1.10.0 and everything worked fine

This would work however, Extra Origins, another addon I'm using, requires Pehkui 2.0.0. Is there a work around to this that you know of?

**Comment by MrLightningBlaze** [comment]
Here, for those of you with this issue, I patched it myself super fast to make it work, it was only a tiny bit of code I needed to change, and might make a pull request shortly with my code changes if the dev wants to pick them up
https://drive.google.com/file/d/1tFouUCXfMmx-1y_d7gvOaZitbi_Yb5sj/view?usp=sharing

**Comment by CritzenMC** [comment]
@MrLightningBlaze how can i install it onto a server??? aternos btw

**Comment by MrLightningBlaze** [comment]
@CritzenMC Its the exact same process as the original mod, I mearly updated some code in it to fix the crashing issue

**Comment by pengolod** [comment]
@MrLightningBlaze could you add your changes as a pull request to the repo so that it might be able to be merged?

**Comment by pengolod** [comment]
> @MrLightningBlaze could you add your changes as a pull request to the repo so that it might be able to be merged?

#10 incorporates your fixes as a PR - hopefully, it'll get merged soon!

**Comment by Jack-Sibley** [comment]
Thank you so much @MrLightningBlaze and @pengolod this has been fixed in v3.0.0
