### ISSUE TITLE
Game doesn’t launch

### ISSUE THREAD

**Issue by AestheticSkye** [Jack-Sibley/slimeorigin#9]
Launcher crashes and shows "exit code 0" (MacOS M1), normal Origins mod works

**Comment by uzervlad** [comment]
This isn't enough to identify the issue, please, attach your crash reports.

**Comment by AestheticSkye** [comment]
[2021-04-27-1 4.log.zip](https://github.com/Jack-Sibley/slimeorigin/files/6387475/2021-04-27-1.4.log.zip)

**Comment by uzervlad** [comment]
Your issue seems to be caused by MobOrigins https://github.com/UltrusBot/MobOrigins/issues/5

**Comment by AestheticSkye** [comment]
Sorry, wrong log. I was testing out different add ons and all of them seem to be doing the same thing
[2021-04-28-1.log.gz](https://github.com/Jack-Sibley/slimeorigin/files/6387660/2021-04-28-1.log.gz)

**Comment by uzervlad** [comment]
You had Fabric 0.10.8, but SlimeOrigin requires versions 0.11.1 or higher

**Comment by AestheticSkye** [comment]
That... would make sense
